export enum Operation {
    ADDITION = "ADDITION",
    SUBTRACTION = "SUBTRACTION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    POWER = "POWER",
    SQUARE_ROOT = "SQUARE_ROOT",
  }